title: hbzkyd
description: 文字描述
url: http://hbzkyd.github.io
# url: http://localhost:4000

links:
  - title: Portfolio
    url: /portfolio
  - title: Contact
    url: /contact

timezone: Asia/Shanghai
future: true
pygments: true
markdown: kramdown

permalink: /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
